title: <p align="center'> Mohammed Feroz K </p>
logo: /assets/img/logo.png

description: 
<p align="center'> 
<a href="pdf/resume.pdf">Resume</a>
<a href="https://www.linkedin.com/in/fermoha/">LinkedIn</a>
<a href="https://www.github.com/ferozmech">GitHub</a>

<br>
I am working  on pursuing my Master degree in Machine Learning & Artificial Inteligence at IITB 
<br>
</p>



theme: jekyll-theme-minimal
